//! Install `claude-trace-rs` as a background service that starts automatically
//! with the user's session, so the dashboard is always running without keeping
//! a terminal open.
//!
//! Each platform uses its native, no-admin-required mechanism:
//! - Linux — a systemd **user** unit (`~/.config/systemd/user/…`).
//! - macOS — a **LaunchAgent** plist (`~/Library/LaunchAgents/…`).
//! - Windows — a hidden VBScript launcher dropped in the **Startup** folder.
//!
//! The unit/plist/script generators are pure functions (and unit-tested); only
//! the install/uninstall steps touch the system.

use std::path::PathBuf;

use anyhow::{Context, Result};

/// Stable identifiers reused across platforms.
#[allow(dead_code)] // used on Linux/Windows only (and in path helpers)
pub const SERVICE_NAME: &str = "claude-trace-rs";
#[allow(dead_code)] // used on macOS only (and in tests)
pub const LAUNCH_LABEL: &str = "rs.claude-trace.claude-trace-rs";

/// Everything needed to render a service definition.
#[derive(Debug, Clone)]
pub struct ServiceConfig {
    /// Absolute path to the `claude-trace-rs` executable.
    pub exe: PathBuf,
    /// Port the dashboard should listen on.
    pub port: u16,
    /// Directories of agent trace logs to watch (one `--watch-root` each).
    pub watch_roots: Vec<String>,
    /// Optional explicit database path.
    pub db: Option<String>,
    /// Open the browser when the service starts.
    pub open: bool,
}

impl ServiceConfig {
    /// The `serve` arguments the service should run with, as a vector.
    fn serve_args(&self) -> Vec<String> {
        let mut a = vec![
            "serve".to_string(),
            "--port".to_string(),
            self.port.to_string(),
        ];
        for root in &self.watch_roots {
            a.push("--watch-root".to_string());
            a.push(root.clone());
        }
        if let Some(db) = &self.db {
            a.push("--db".to_string());
            a.push(db.clone());
        }
        if self.open {
            a.push("--open".to_string());
        }
        a
    }
}

/// systemd user unit file contents.
#[allow(dead_code)] // platform-specific (Linux), exercised by tests
pub fn systemd_unit(cfg: &ServiceConfig) -> String {
    let args = cfg.serve_args().join(" ");
    format!(
        "[Unit]\n\
         Description=Claude Trace — Claude Code observability dashboard\n\
         After=network.target\n\n\
         [Service]\n\
         Type=simple\n\
         ExecStart={exe} {args}\n\
         Restart=on-failure\n\
         RestartSec=3\n\n\
         [Install]\n\
         WantedBy=default.target\n",
        exe = cfg.exe.display(),
        args = args,
    )
}

/// launchd LaunchAgent plist contents.
#[allow(dead_code)] // platform-specific (macOS), exercised by tests
pub fn launchd_plist(cfg: &ServiceConfig) -> String {
    let mut program_args = String::new();
    program_args.push_str(&format!(
        "    <string>{}</string>\n",
        xml_escape(&cfg.exe.to_string_lossy())
    ));
    for a in cfg.serve_args() {
        program_args.push_str(&format!("    <string>{}</string>\n", xml_escape(&a)));
    }
    let log = "${HOME}/Library/Logs/claude-trace-rs.log";
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n\
         <plist version=\"1.0\">\n\
         <dict>\n\
         \x20 <key>Label</key>\n  <string>{label}</string>\n\
         \x20 <key>ProgramArguments</key>\n  <array>\n{args}  </array>\n\
         \x20 <key>RunAtLoad</key>\n  <true/>\n\
         \x20 <key>KeepAlive</key>\n  <true/>\n\
         \x20 <key>StandardOutPath</key>\n  <string>{log}</string>\n\
         \x20 <key>StandardErrorPath</key>\n  <string>{log}</string>\n\
         </dict>\n\
         </plist>\n",
        label = LAUNCH_LABEL,
        args = program_args,
        log = log,
    )
}

/// Hidden Windows startup launcher (VBScript runs the exe with no console).
#[allow(dead_code)] // platform-specific (Windows), exercised by tests
pub fn windows_vbs(cfg: &ServiceConfig) -> String {
    let mut cmd = format!("\"\"{}\"\"", cfg.exe.display());
    for a in cfg.serve_args() {
        if a.contains(' ') {
            cmd.push_str(&format!(" \"\"{a}\"\""));
        } else {
            cmd.push(' ');
            cmd.push_str(&a);
        }
    }
    format!(
        "' Auto-generated by `claude-trace-rs service install`.\r\n\
         Set sh = CreateObject(\"WScript.Shell\")\r\n\
         sh.Run \"{cmd}\", 0, False\r\n",
        cmd = cmd,
    )
}

#[allow(dead_code)] // platform-specific (macOS), exercised by tests
fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

// ---------------------------------------------------------------------------
// Install / uninstall / status (platform-specific side effects)
// ---------------------------------------------------------------------------

#[cfg(all(unix, not(target_os = "macos")))]
fn unit_path() -> Result<PathBuf> {
    let base = directories::BaseDirs::new().context("no home directory")?;
    Ok(base
        .config_dir()
        .join("systemd/user")
        .join(format!("{SERVICE_NAME}.service")))
}

#[cfg(target_os = "macos")]
fn plist_path() -> Result<PathBuf> {
    let base = directories::BaseDirs::new().context("no home directory")?;
    Ok(base
        .home_dir()
        .join("Library/LaunchAgents")
        .join(format!("{LAUNCH_LABEL}.plist")))
}

#[cfg(target_os = "windows")]
fn startup_path() -> Result<PathBuf> {
    let appdata = std::env::var("APPDATA").context("APPDATA not set")?;
    Ok(PathBuf::from(appdata)
        .join("Microsoft/Windows/Start Menu/Programs/Startup")
        .join(format!("{SERVICE_NAME}.vbs")))
}

#[allow(dead_code)] // used by the platform-specific install paths
fn write_file(path: &std::path::Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(path, contents).with_context(|| format!("writing {}", path.display()))?;
    Ok(())
}

#[allow(dead_code)] // used by the platform-specific install/uninstall paths
fn run(cmd: &str, args: &[&str]) -> bool {
    match std::process::Command::new(cmd).args(args).status() {
        Ok(s) => s.success(),
        Err(_) => false,
    }
}

/// Install and start the background service for the current user.
#[cfg(all(unix, not(target_os = "macos")))]
pub fn install(cfg: &ServiceConfig) -> Result<()> {
    let path = unit_path()?;
    write_file(&path, &systemd_unit(cfg))?;
    println!("Wrote systemd user unit: {}", path.display());

    run("systemctl", &["--user", "daemon-reload"]);
    let unit = format!("{SERVICE_NAME}.service");
    if run("systemctl", &["--user", "enable", "--now", &unit]) {
        println!("✓ Service enabled and started.");
        println!(
            "  Tip: run `loginctl enable-linger $USER` so it keeps running when you're logged out."
        );
        println!("  Dashboard: http://127.0.0.1:{}/", cfg.port);
    } else {
        println!("Unit installed, but `systemctl --user enable --now` failed.");
        println!("Enable it manually with:\n  systemctl --user daemon-reload && systemctl --user enable --now {unit}");
    }
    Ok(())
}

#[cfg(target_os = "macos")]
pub fn install(cfg: &ServiceConfig) -> Result<()> {
    let path = plist_path()?;
    write_file(&path, &launchd_plist(cfg))?;
    println!("Wrote LaunchAgent: {}", path.display());
    let p = path.to_string_lossy().to_string();
    // Reload if already present, then load enabled.
    run("launchctl", &["unload", &p]);
    if run("launchctl", &["load", "-w", &p]) {
        println!("✓ Service loaded and started.");
        println!("  Dashboard: http://127.0.0.1:{}/", cfg.port);
    } else {
        println!("Plist installed, but `launchctl load` failed. Load it manually with:\n  launchctl load -w {p}");
    }
    Ok(())
}

#[cfg(target_os = "windows")]
pub fn install(cfg: &ServiceConfig) -> Result<()> {
    let path = startup_path()?;
    write_file(&path, &windows_vbs(cfg))?;
    println!("Installed startup launcher: {}", path.display());
    println!("It will start automatically next time you sign in.");
    // Start it now, hidden, without waiting.
    let args = cfg.serve_args();
    let arg_refs: Vec<&str> = args.iter().map(String::as_str).collect();
    let _ = std::process::Command::new(&cfg.exe).args(&arg_refs).spawn();
    println!("✓ Started now.  Dashboard: http://127.0.0.1:{}/", cfg.port);
    Ok(())
}

/// Stop and remove the background service.
#[cfg(all(unix, not(target_os = "macos")))]
pub fn uninstall() -> Result<()> {
    let unit = format!("{SERVICE_NAME}.service");
    run("systemctl", &["--user", "disable", "--now", &unit]);
    let path = unit_path()?;
    if path.exists() {
        std::fs::remove_file(&path).ok();
        println!("Removed {}", path.display());
    }
    run("systemctl", &["--user", "daemon-reload"]);
    println!("✓ Service uninstalled.");
    Ok(())
}

#[cfg(target_os = "macos")]
pub fn uninstall() -> Result<()> {
    let path = plist_path()?;
    if path.exists() {
        run("launchctl", &["unload", &path.to_string_lossy()]);
        std::fs::remove_file(&path).ok();
        println!("Removed {}", path.display());
    }
    println!("✓ Service uninstalled.");
    Ok(())
}

#[cfg(target_os = "windows")]
pub fn uninstall() -> Result<()> {
    let path = startup_path()?;
    if path.exists() {
        std::fs::remove_file(&path).ok();
        println!("Removed {}", path.display());
    }
    println!("✓ Startup launcher removed. Stop any running instance from Task Manager.");
    Ok(())
}

/// Report whether the service is installed/running.
#[cfg(all(unix, not(target_os = "macos")))]
pub fn status() -> Result<()> {
    let path = unit_path()?;
    println!(
        "Unit file: {} ({})",
        path.display(),
        if path.exists() { "present" } else { "absent" }
    );
    let unit = format!("{SERVICE_NAME}.service");
    run("systemctl", &["--user", "status", "--no-pager", &unit]);
    Ok(())
}

#[cfg(target_os = "macos")]
pub fn status() -> Result<()> {
    let path = plist_path()?;
    println!(
        "LaunchAgent: {} ({})",
        path.display(),
        if path.exists() { "present" } else { "absent" }
    );
    run("launchctl", &["list", LAUNCH_LABEL]);
    Ok(())
}

#[cfg(target_os = "windows")]
pub fn status() -> Result<()> {
    let path = startup_path()?;
    println!(
        "Startup launcher: {} ({})",
        path.display(),
        if path.exists() { "present" } else { "absent" }
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg() -> ServiceConfig {
        ServiceConfig {
            exe: PathBuf::from("/usr/local/bin/claude-trace-rs"),
            port: 7779,
            watch_roots: vec!["/home/me/.claude/projects".into()],
            db: Some("/data/trace.db".into()),
            open: false,
        }
    }

    #[test]
    fn systemd_unit_has_execstart_with_args() {
        let u = systemd_unit(&cfg());
        assert!(u.contains("ExecStart=/usr/local/bin/claude-trace-rs serve --port 7779"));
        assert!(u.contains("--watch-root /home/me/.claude/projects"));
        assert!(u.contains("--db /data/trace.db"));
        assert!(u.contains("WantedBy=default.target"));
    }

    #[test]
    fn launchd_plist_is_well_formed() {
        let p = launchd_plist(&cfg());
        assert!(p.contains("<key>Label</key>"));
        assert!(p.contains(LAUNCH_LABEL));
        assert!(p.contains("<string>serve</string>"));
        assert!(p.contains("<key>RunAtLoad</key>"));
    }

    #[test]
    fn windows_vbs_runs_hidden() {
        let v = windows_vbs(&cfg());
        assert!(v.contains("sh.Run"));
        assert!(v.contains(", 0, False")); // hidden window, non-blocking
        assert!(v.contains("serve"));
    }

    #[test]
    fn open_flag_is_propagated() {
        let mut c = cfg();
        c.open = true;
        assert!(systemd_unit(&c).contains("--open"));
    }
}
